### ISSUE TITLE
ll.c : TM_THREAD_STOP and TM_STOP after all the ll_size

### ISSUE THREAD

**Issue by Gilthoniel** [LPD-EPFL/ca15-stm#1]
Hi,

A problem occured when you free what you use in the transactions because you use the TM_\* freeing functions (line 415) and just after, you check the size of the list with ll_size, in which we use a transaction => Seg fault

Simple solution is to move the two freeing functions just before TM_STATS (line 464)

**Comment by trigonak** [comment]
Good point, thanks. Just pushed a fix.
