### ISSUE TITLE
`ll` and `bank` only use one thread

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [LPD-EPFL/ca15-stm#3]
Hello,

I'm unable to run the example programs on multiple thread (while there are 12 available). It only use one is it normal ?

**Comment by GuillaumeLeclerc** [comment]
I found out about the `-n` parameter but I think it has his place in the help section as it is probably the most important parameter.

**Comment by trigonak** [comment]
Added -n in the output of -h
