### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [LPD-EPFL/ca15-stm#5]
I did the project with C++ instead of C++ but I face a linking problem.

the function `stm_tx_store` is marked as `extern inline`. For that reason when I build the static library the symbol is removed from the archive (because it is inline)

When I need to build my test program then it searches the `stm_tx_store` symbol which is not in libsstm.a

I see two options:
- Compile my test program along with the `sstm.cpp` file to make it aware of the code inside the inlined function, but it break the advantage of having a library.
- Remove the `inline` keyword in `store` and `load` functions

By the way I still don't get how it works with `C`. An `inline` function in a library does not make sense to me. Does it extract the binary code from the library and then inject it in the program that use the library ?

**Comment by trigonak** [comment]
I see the problem. 
You can adjust the code according to https://stackoverflow.com/questions/10291581/how-to-properly-inline-for-static-libraries

**Comment by GuillaumeLeclerc** [comment]
Thank you but I can't do this.

If I understood well I should basically move the inline implementation in the header file. My implementation is in C++, Then the two executables, bank and ll are written in C they can't import C++ header file.

Did I miss something ?

**Comment by trigonak** [comment]
Maybe try to add the header files in the library, or change `back.c` and `ll.c` to C++.
